### ISSUE TITLE
Problem with spinner input value updating

### ISSUE THREAD

**Issue by leathrum** [Ali-Azmoud/spinner_input#1]
When you update the value of the variable affected by a SpinnerInput widget with an action from another widget, at first the value is changed correctly, but then when you use the spinner's buttons again, it acts as though the update never happened.

I don't think I am missing anything about how the SpinnerInput is supposed to be used, and I have tried several things to address this problem, but nothing seems to work.

I have included a complete minimal app below showing the problem, but here is the key bit of the code:

```dart
            SpinnerInput(
              minValue: 1,
              maxValue: 50,
              step: 1,
              spinnerValue: _spinnervalue,
              onChange: (value) {setState(() {_spinnervalue = value;});},
            ),
            RaisedButton(
                onPressed: () {setState(() {_spinnervalue = initialvalue;});},
              child: Text('Clear')
            ),
```
In the running app, click the "+" button a few times, say to take the value from 20 up to 25.  Then click the "Clear" button -- this sets the value of the spinner back to its initial value of 20.  Then click "+" again, just once, and it shows... 26?!  It's like you never hit the "Clear" button.

If I'm just doing something wrong here, please let me know, but I think the problem is deeper than that.

Here is the complete Flutter app code:

```dart
import 'package:flutter/material.dart';
import 'package:spinner_input/spinner_input.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Spinner Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Spinner Test Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _spinnervalue = 20;
  final double _initialvalue = 20;

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            SpinnerInput(
              minValue: 1,
              maxValue: 50,
              step: 1,
              spinnerValue: _spinnervalue,
              onChange: (value) {setState(() {_spinnervalue = value;});},
            ),
            RaisedButton(
                onPressed: () {setState(() {_spinnervalue = _initialvalue;});},
              child: Text('Clear')
            ),
          ],
        ),
      ),
    );
  }
}
```
My use case where this appeared:  I have several of these SpinnerInput widgets in an app, and I want to have a single button that the user can click to set all of the spinners back to their initial default values.  As seen in the app above, the behavior of the SpinnerInput widget _after_ the action of the button has occurred is not correct for this use.

**Comment by Ali-Azmoud** [comment]
Hi @leathrum 
Sorry for the late reply. I updated the package. you should be able to do that now.

**Comment by leathrum** [comment]
I'm still getting the same incorrect behavior with the updated package.  I appreciate your effort, but it looks like you need to re-open this.

**Comment by Ali-Azmoud** [comment]
@leathrum 
I copied your code and tested it. it's working as expected. make sure you've updated the package

**Comment by leathrum** [comment]
I checked the package version on my end -- in my test app as above, the pubspec.yaml specifies spinner_input v0.1.2  and I ran the flutter packages upgrade command, no problems reported.  Building and running the app from scratch with that, I still get the incorrect behavior.  I don't know if this matters, but the Flutter package page at pub.dartlang.org shows v0.1.2 updated 5/2/19, and the github page shows no updates since February.  Maybe the new version hasn't propagated to where I can get it yet?  I'm not sure how that works for Flutter packages...

**Comment by Ali-Azmoud** [comment]
just edit `pubspec.yaml` file to version `v0.1.2` and run this command in a terminal in the same directory of `pubspec.yaml` file.

``` flutter packages get ```

 if you have `VSCode` or `Android Studio`  just open a terminal tab and run the command. to make sure your package is updated. open `Dart Packages` directory and check the version of your desired package.

**Comment by leathrum** [comment]
I finally got the right version of the package to load, pretty much by accident though.  I am using Android Studio, and I had already done everything you suggested -- edit pubspec.yaml to specify v0.1.2, click "packages get" (I also tried "packages upgrade" just to be sure), recompile and run in the emulator.  I even tried restarting the emulator from scratch, just to be sure it didn't somehow hang onto the old version.  That all still gave me the old package with the incorrect behavior.  What finally worked, I did entirely by mistake:  I edited the pubspec.yaml to specify version 0.1.3 and clicked "packages get" before I realized my mistake.  Of course that generated an error, at which point I realized what I had done, fixed it, and clicked "packages get" again.  This time, for whatever reason, it worked, I now have the updated package.  So... Thank you!  It works fine now.

I may have a separate feature request for this package at some point, too, but it isn't as urgent and I am still trying to see if I can get the feature to work in my own code first.  I'll let you know.

**Comment by Ali-Azmoud** [comment]
Sometimes, clicking on `packages get` in `Android Studio` doesn't work. I don't know why this happens but my be it caches or something else. I personally most of the time type the command `flutter packages get` in a terminal tab to make it work.

**Comment by vincperrone** [comment]
Hi, @Ali-Azmoud I have the same problem with version 0.1.2.
this is my code:

```javascript
Future<void> _setCustomHours() async {
    return showDialog<void>(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Set hours', textAlign: TextAlign.center,),
          content: SingleChildScrollView(
            child: ListBody(
              mainAxis: Axis.vertical,
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(
                    top:15.0
                  ),
                ),
                Center(
                  child: SpinnerInput(
                    minValue: 1,
                    maxValue: 10,
                    step: 0.5,
                    fractionDigits: 1,
                    disabledLongPress: true,
                    disabledPopup: true,
                    plusButton: SpinnerButtonStyle(
                      elevation: 3, 
                      height: 40,
                      width: 40,
                      color: Colors.grey[300], 
                      textColor: Colors.black, 
                      borderRadius: BorderRadius.circular(3)
                    ),
                    minusButton: SpinnerButtonStyle(
                      elevation: 3, 
                      height: 40,
                      width: 40,
                      color: Colors.grey[300], 
                      textColor: Colors.black, 
                      borderRadius: BorderRadius.circular(3)
                    ),
                    middleNumberWidth: 80,
                    middleNumberStyle: TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.bold
                    ),
                    spinnerValue: hours, //hours is a double initialized to 1.0 in the State
                    onChange: (newValue) {
                      setState(() => hours = newValue);
                    },
                  ),
                ),
              ],
            ),
          ),
          actions: <Widget>[
            FlatButton(
              child: Text('OK'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            )
          ],
        );
      },
    );
  }
```

When the app starts, I see the value 1.0.
If I tap + or - the value in the state gets updated, while the value I see on the view is still 1.0...

Any idea?
Thanks

**Comment by muhd-ameen** [comment]
> Hi, @Ali-Azmoud I have the same problem with version 0.1.2. this is my code:
> 
> ```js
> Future<void> _setCustomHours() async {
>     return showDialog<void>(
>       context: context,
>       barrierDismissible: false,
>       builder: (BuildContext context) {
>         return AlertDialog(
>           title: Text('Set hours', textAlign: TextAlign.center,),
>           content: SingleChildScrollView(
>             child: ListBody(
>               mainAxis: Axis.vertical,
>               children: <Widget>[
>                 Padding(
>                   padding: EdgeInsets.only(
>                     top:15.0
>                   ),
>                 ),
>                 Center(
>                   child: SpinnerInput(
>                     minValue: 1,
>                     maxValue: 10,
>                     step: 0.5,
>                     fractionDigits: 1,
>                     disabledLongPress: true,
>                     disabledPopup: true,
>                     plusButton: SpinnerButtonStyle(
>                       elevation: 3, 
>                       height: 40,
>                       width: 40,
>                       color: Colors.grey[300], 
>                       textColor: Colors.black, 
>                       borderRadius: BorderRadius.circular(3)
>                     ),
>                     minusButton: SpinnerButtonStyle(
>                       elevation: 3, 
>                       height: 40,
>                       width: 40,
>                       color: Colors.grey[300], 
>                       textColor: Colors.black, 
>                       borderRadius: BorderRadius.circular(3)
>                     ),
>                     middleNumberWidth: 80,
>                     middleNumberStyle: TextStyle(
>                       fontSize: 14,
>                       fontWeight: FontWeight.bold
>                     ),
>                     spinnerValue: hours, //hours is a double initialized to 1.0 in the State
>                     onChange: (newValue) {
>                       setState(() => hours = newValue);
>                     },
>                   ),
>                 ),
>               ],
>             ),
>           ),
>           actions: <Widget>[
>             FlatButton(
>               child: Text('OK'),
>               onPressed: () {
>                 Navigator.of(context).pop();
>               },
>             )
>           ],
>         );
>       },
>     );
>   }
> ```
> 
> When the app starts, I see the value 1.0. If I tap + or - the value in the state gets updated, while the value I see on the view is still 1.0...
> 
> Any idea? Thanks


I have also the same Issue ! any Idea.
